- src/Compat/FilterProcessor.php
blocked by https://github.com/Icinga/ipl-stdlib/pull/20
> Utilize native filter meta data instead of properties

- src/Compat/FilterProcessor.php
- src/Query.php
- src/ResolvedExpression.php
- src/Resolver.php
- tests/Car.php
- tests/Passenger.php
- tests/QueryTest.php
- tests/ResolverTest.php
Notable changes:
* `Resolver::requireAndResolveColumns()` now transforms instances of `ipl\Sql\Expression` to `ipl\Orm\ResolvedExpression` which can't be used further without being qualified
* Removed `array` type declaration for param `$columns` in `Resolver::qualifyColumnsAndAliases()` to allow passing the result of `Resolver::requireAndResolveColumns()`
* Re-introduced `Resolver::qualifyColumns()`
> Qualify and resolve expression columns correctly

- src/Query.php
closes https://github.com/Icinga/ipl-sql/pull/45
refs https://github.com/Icinga/ipl-orm/pull/26
> Query: Add possibility to disable default sorting

- src/Relation/BelongsToMany.php
- tests/BelongsToManyTest.php
- tests/Car.php
- tests/CarUser.php
- tests/CarUserWithCustomKeys.php
- tests/User.php
Previously, when using a through model that sets custom keys,
the keys from the through model to the target model were the wrong
way round. This PR doesn't fix that it might make sense to let the
first custom key defined win instead of the last.
> Properly respect custom keys in through models

- src/Query.php
- src/Resolver.php
- tests/ResolverTest.php
This is an unimplemented feature yet, but behaviors may be query dependent and the resolver allows for lazy initialization of the query, which makes things unnecessarily complicated when implementing this feature.
The resolver is dependent on the query anyway, so it's easier if the query is already required to build the resolver.
> Require Query in Resolver::__construct()

- src/Compat/FilterProcessor.php
Previously, the filter processor considered only with()ed relations when
deciding whether to perform a subquery filter. utilize()d relations are
now also taken into account.
> Don't perform subquery filter on utilized()d relations

- src/Query.php
- src/Resolver.php
- tests/ApiIdentity.php
- tests/QueryTest.php
- tests/SqlTest.php
- tests/TestModelWithAliasedColumns.php
- tests/User.php
Tested with MySQL and PostgreSQL using custom variables and other relations. (e.g. `hostgroup.name` and `user.name`)
> Allow order by aliased expressions

- src/Query.php
- src/Resolver.php
- tests/QueryTest.php
- tests/SqlTest.php
This PR no longer makes `Query::columns()` additive and introduces `Query::withColumns()` to specify additional columns to select. This allows us to control at any point in time which columns should be selected exactly, but also specify additional columns if necessary.
closes #58
> Change column methods

- src/Behaviors.php
- src/ColumnDefinition.php
- src/Contract/RewriteColumnBehavior.php
- src/Model.php
- src/Resolver.php
- tests/ApiIdentity.php
Introduces a new class (`ColumnDefinition`) which purpose is to describe a column. Currently only a label can be provided. In the future we might extend this to provide datatypes and other useful information.
The interface `RewriteColumnBehavior` (introduced by #63) has also been extended by two new methods: `rewriteColumnDefinition` and `isSelectableColumn`
A behavior that is able to return *any* expression in `rewriteColumn` should be able to provide a definition and tell if it does provide such a column when being asked for it.
Method `getMetaData` of class `Model` has been renamed to `getColumnDefinitions`, to match the new type. Similarly `Resolver::getMetaData` is now `Resolver::getColumnDefinitions`, which also doesn't return any other definitions than those of the given model now. …
> Introduce column definitions

- src/Behavior/Binary.php
Otherwise the behavior throws an exception because it requires a
resource in fromDb(). This was created with the background that values
are only retrieved from the database via PDO. However, since behaviors
can be executed explicitly, any value can be passed from any source.
This must not fail if the value is not a resource. For example, we do
this in Icinga DB Web for values read from Redis.
fixes Icinga/ipl-orm#69
> Binary behavior: Return non-resource as is

- src/ResultSet.php
- tests/ResultSetTest.php
Earlier ResultSet::position was not incremented once the cache is filled and hence ResultSet::valid() was
not functioning as expected. Hence, Icinga\Module\Icingadb\Widget\ShowMore was not working as expected.
This fix resolves the issue.
fix Icinga/icingadb-web/issues/540
> Fix ResultSet::next() to increment ResultSet::position when ResultSet::cache is valid

- src/Behavior/BoolCast.php
- tests/Behavior/BoolCastTest.php
The BoolCast behavior is based on the behavior of Icinga DB Web, but implements a common usage:
- `y`/`n` are the default values for true and false, but can be overridden.
- The default mode is **strict**, meaning that if the value does not match the true or false value, an exception is thrown. However, this can be overridden so that a non-matching value is passed untouched.
> Add BoolCast behavior

- composer.json
- src/Query.php
- tests/QueryTest.php
When using something like this, a fatal PHP error occurs:
```php
$query->orderBy(new Expression('cnt DESC, certificate_issuer.subject')
```
```php
Uncaught TypeError: Illegal offset type in isset or empty in /usr/local/src/ipl-orm/src/Query.php:727
Stack trace:
#0 /usr/local/src/ipl-orm/src/Query.php(492): ipl\Orm\Query->order(Object(ipl\Sql\Select))
#1 /usr/local/src/ipl-orm/src/Query.php(641): ipl\Orm\Query->assembleSelect()
#2 /usr/local/src/ipl-orm/src/ResultSet.php(142): ipl\Orm\Query->yieldResults()
#3 [internal function]: ipl\Orm\ResultSet->yieldTraversable(Object(Generator))
#4 /usr/local/src/ipl-orm/src/ResultSet.php(122): Generator->valid()
#5 /usr/local/src/ipl-orm/src/ResultSet.php(114): ipl\Orm\ResultSet->advance()
#6 …
```
> Query: Fix order by expression causes fatal error

- src/Behavior/Binary.php
- src/Compat/FilterProcessor.php
- tests/Behavior/BinaryTest.php
This now makes it possible to extend the `Binary` behaviour and to additionally apply other behaviours to the mysql adapter as well, such as the `IP` behaviour of the `x509` module.
fixes https://github.com/Icinga/icingaweb2-module-x509/issues/172
> Make `Binary` behaviour extensible which might also be used for mysql adapter

- src/Compat/FilterProcessor.php
- src/Query.php
requires https://github.com/Icinga/ipl-sql/pull/74
> Use `IN` instead of `EXISTS` to resolve to-n relation filters

- phpstan-baseline.neon
- src/Common/SortUtil.php
`createOrderBy()` can never return null.
> SortUtil: Fix return type hint of `createOrderBy()`

- phpstan-baseline.neon
- src/Behavior/Binary.php
- src/Compat/FilterProcessor.php
This change prevents now the subject behaviors from being applied for the same filter condition over again when it's wrapped into a subquery. This PR removes also the (now obsolete if condition) from the binary behaviour.
fixes #48
closes https://github.com/Icinga/icingaweb2-module-x509/pull/174
> Do not apply behaviors twice

- src/Contract/PropertyBehavior.php
`retrieve()` may be called hundreds if not even thousands of times. If for each call, even a small subset of properties doesn't exist, PHP will throw `OutOfBoundsException` for hundreds or thousands of times as well. Checking is way less expensive than throwing an error this often.
Speeds up queries with limited select lists and many model behaviors significantly.
> PropertyBehavior: Check if a property exists before accessing it

- src/Hydrator.php
- tests/HydratorTest.php
- tests/User.php
> Hydrator: Correctly hydrate custom aliases targeting targets with underscores in their name

- src/Hydrator.php
- tests/HydratorTest.php
> Hydrator: Properly hydrate custom columns if an alias prefix is used

- src/Query.php
- tests/QueryTest.php
Excluding a column from a query/model that also contains expression columns fails as follows: I originally noticed this when working on https://github.com/Icinga/icingaweb2-module-nagvis/pull/61 where I wanted to exclude some columns from the `ServicestateSummary` model that were causing a PostgreSQL grouping error, but you can also easily trigger this in Icinga DB Web by adding `$servicegroupss->withoutColumns(‘id’);` in `ServicegroupsController` for example.
> Query: Determine omitted & target columns correctly

- src/Query.php
- tests/QueryTest.php
Otherwise, the query fails if `Query::orderBy()` contain relations that are not present in `Query::$with`.
- Previously, `Query::order()` enhanced the `Query::$with` array, but the enhanced values were no longer taken into account for joining relations.
> Query::assembleSelect(): Apply `orderBy` before joining the relations
